server:
    port: 8083
    context-path: /ui2
    session:
      cookie:
        name: UI2SESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://quiet-atoll-49433.herokuapp.com/auth/oauth/token
      userAuthorizationUri: http://quiet-atoll-49433.herokuapp.com/auth/oauth/authorize
    resource:
      userInfoUri: http://quiet-atoll-49433.herokuapp.com/auth/user/me
spring:
  thymeleaf:
    cache: false        